from __future__ import annotations

import argparse
import csv
import json
import mimetypes
import re
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


GT_ALIASES = {
    "melanoma": "melanoma",
    "malignant": "melanoma",
    "suspicious": "melanoma",
    "nevus": "nevus",
    "nevi": "nevus",
    "melanocytic_nevi": "nevus",
    "melanocytic_nevus": "nevus",
    "benign": "nevus",
    "nonsuspicious": "nevus",
    "non_suspicious": "nevus",
    "non suspicious": "nevus",
}


def normalize_label(label: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", label.strip().lower()).strip("_")
    return GT_ALIASES.get(normalized, normalized)


def build_multipart_body(field_name: str, file_path: Path) -> tuple[bytes, str]:
    boundary = f"----WebKitFormBoundary{uuid.uuid4().hex}"
    content_type = mimetypes.guess_type(str(file_path))[0] or "application/octet-stream"
    filename = file_path.name
    file_bytes = file_path.read_bytes()

    body = (
        f"--{boundary}\r\n"
        f"Content-Disposition: form-data; name=\"{field_name}\"; filename=\"{filename}\"\r\n"
        f"Content-Type: {content_type}\r\n\r\n"
    ).encode("utf-8") + file_bytes + f"\r\n--{boundary}--\r\n".encode("utf-8")

    return body, boundary


def post_infer(endpoint: str, image_path: Path, timeout_seconds: float) -> dict[str, Any]:
    body, boundary = build_multipart_body(field_name="file", file_path=image_path)
    request = Request(
        endpoint,
        data=body,
        method="POST",
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
    )

    with urlopen(request, timeout=timeout_seconds) as response:
        payload = response.read().decode("utf-8")
        return json.loads(payload)


def resolve_image_path(manifest_path: Path, raw_path: str) -> Path:
    candidate = Path(raw_path)
    if candidate.exists():
        return candidate

    manifest_relative = (manifest_path.parent / raw_path).resolve()
    if manifest_relative.exists():
        return manifest_relative

    raise FileNotFoundError(f"Image not found: {raw_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate /infer accuracy against a labeled manifest")
    parser.add_argument(
        "--manifest",
        default="test_samples/ham10000/manifest.csv",
        help="Path to CSV manifest generated by pull_labeled_test_images.py",
    )
    parser.add_argument(
        "--endpoint",
        default="http://127.0.0.1:8000/infer",
        help="Inference endpoint",
    )
    parser.add_argument("--timeout", type=float, default=20.0, help="HTTP timeout in seconds")
    parser.add_argument(
        "--report-out",
        default="test_samples/ham10000/eval_report.json",
        help="Where to write JSON evaluation report",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Optional max number of rows to evaluate (0 = all)",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    report_out = Path(args.report_out)
    report_out.parent.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, str]] = []
    with manifest_path.open("r", newline="") as fp:
        reader = csv.DictReader(fp)
        rows = list(reader)

    if args.limit > 0:
        rows = rows[: args.limit]

    if not rows:
        raise ValueError("Manifest contains no rows to evaluate")

    evaluated = 0
    correct = 0
    failures: list[dict[str, str]] = []
    per_class_total: dict[str, int] = defaultdict(int)
    per_class_correct: dict[str, int] = defaultdict(int)
    confusion: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    details: list[dict[str, Any]] = []

    for row in rows:
        gt_raw = row.get("label", "")
        file_raw = row.get("filename", "")
        image_id = row.get("image_id", "")

        if not gt_raw or not file_raw:
            failures.append({"image_id": image_id, "error": "Missing label or filename in manifest row"})
            continue

        gt = normalize_label(gt_raw)

        try:
            image_path = resolve_image_path(manifest_path, file_raw)
            response = post_infer(args.endpoint, image_path, args.timeout)
            pred_raw = str(response.get("label", ""))
            pred = normalize_label(pred_raw)
            confidence = float(response.get("confidence", 0.0))
        except (FileNotFoundError, HTTPError, URLError, TimeoutError, ValueError, json.JSONDecodeError) as exc:
            failures.append({"image_id": image_id, "error": str(exc)})
            continue

        is_correct = pred == gt
        evaluated += 1
        per_class_total[gt] += 1
        if is_correct:
            correct += 1
            per_class_correct[gt] += 1
        confusion[gt][pred] += 1

        details.append(
            {
                "image_id": image_id,
                "filename": file_raw,
                "ground_truth": gt,
                "predicted": pred,
                "predicted_raw": pred_raw,
                "confidence": confidence,
                "correct": is_correct,
            }
        )

    overall_accuracy = (correct / evaluated) if evaluated else 0.0

    per_class_accuracy = {
        label: {
            "correct": per_class_correct[label],
            "total": total,
            "accuracy": (per_class_correct[label] / total) if total else 0.0,
        }
        for label, total in sorted(per_class_total.items())
    }

    confusion_dict = {
        gt_label: dict(sorted(pred_map.items()))
        for gt_label, pred_map in sorted(confusion.items())
    }

    report: dict[str, Any] = {
        "endpoint": args.endpoint,
        "manifest": str(manifest_path),
        "evaluated": evaluated,
        "correct": correct,
        "accuracy": overall_accuracy,
        "failed": len(failures),
        "per_class_accuracy": per_class_accuracy,
        "confusion": confusion_dict,
        "failures": failures,
        "details": details,
    }

    report_out.write_text(json.dumps(report, indent=2))

    print(f"Evaluated: {evaluated}")
    print(f"Correct: {correct}")
    print(f"Accuracy: {overall_accuracy:.4f}")
    print(f"Failed: {len(failures)}")
    print(f"Report: {report_out}")


if __name__ == "__main__":
    main()
